# Generated by Django 4.2.7 on 2023-12-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='load_approve',
        ),
        migrations.AddField(
            model_name='transaction',
            name='loan_approve',
            field=models.BooleanField(default=False),
        ),
    ]
